{:gsparameter=>
  {:description=>"",
   :should_include=>"true",
   :variables=>
    {:iecom=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iecom,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iptype=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iptype,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iftype=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iftype,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ibtype=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ibtype,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :file_prof=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:file_prof,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :file_bc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:file_bc,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :file_efit=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:file_efit,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :file_tflow=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:file_tflow,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :nt1=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nt1,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nt2=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nt2,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :klag=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:klag,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ksamp=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ksamp,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ksamp2=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ksamp2,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nsub=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nsub,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :kcheb=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:kcheb,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :eps=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:eps,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :epsiter=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:epsiter,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :epslag=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:epslag,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :epslag2=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:epslag2,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :maxiter=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:maxiter,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :epsmaxdist=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:epsmaxdist,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :nchq=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nchq,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nflx=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nflx,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :psiflx=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:psiflx,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :reps=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:reps,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rkappa=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rkappa,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :delta=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:delta,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :r0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:r0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rmid=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rmid,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :z0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:z0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :q0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:q0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :f0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:f0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :fedge=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:fedge,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :p0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:p0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :pin=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:pin,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :pout=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:pout,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ff0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ff0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ffin=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ffin,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ffout=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ffout,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ptf0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ptf0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ptfin=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ptfin,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ptfout=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ptfout,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ptfmax=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ptfmax,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ptfloc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ptfloc,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ptfw=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ptfw,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :mach=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:mach,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :isymud=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:isymud,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ifpol=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ifpol,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :torcur=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:torcur,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :lambdaex=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:lambdaex,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :iprintsol=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iprintsol,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iprintsoldisk=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iprintsoldisk,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iprintcon=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iprintcon,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iprintqs=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iprintqs,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ifitmil=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ifitmil,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iscale=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iscale,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iprintmap=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iprintmap,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :itftype=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:itftype,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :qfac=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qfac,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :qpin=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qpin,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :qpout=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:qpout,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ffac=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ffac,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :fpin=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:fpin,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :fpout=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:fpout,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :iqtype=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iqtype,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :file_qprof=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:file_qprof,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :jpar0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:jpar0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :jpin=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:jpin,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :jpout=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:jpout,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ijtype=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ijtype,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :file_jprof=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:file_jprof,
       :must_pass=>
        [{:test=>"kind_of? String",
          :explanation=>"This variable must be a string."}],
       :type=>:String},
     :iconvq=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iconvq,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iconvj=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iconvj,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :maxdpsiq=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:maxdpsiq,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :relaxiter=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:relaxiter,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :maxdpsij=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:maxdpsij,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :jomax=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:jomax,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :joloc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:joloc,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :jow=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:jow,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :maxiterf=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:maxiterf,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :istability=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:istability,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ibscur=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ibscur,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nchy=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nchy,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ijbsmodel=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ijbsmodel,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :vloop0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:vloop0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :vloop=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:vloop,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ifindmagaxis=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ifindmagaxis,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :epsmag=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:epsmag,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :dpsistartmag=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:dpsistartmag,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :iprintefit=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iprintefit,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :dense0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:dense0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :denseb=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:denseb,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rn1de=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rn1de,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rn2de=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rn2de,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :te0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:te0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :teb=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:teb,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rn1te=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rn1te,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rn2te=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rn2te,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :ti0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ti0,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :tib=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:tib,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rn1ti=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rn1ti,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :rn2ti=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:rn2ti,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :npsi=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:npsi,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :itrinity=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:itrinity,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :ntpsi=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:ntpsi,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :nttin=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:nttin,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :dpsistartnchq=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:dpsistartnchq,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :isplch=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:isplch,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iptable=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iptable,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :irho=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:irho,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iqconstraint=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iqconstraint,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iguessrmap0=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iguessrmap0,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :pgmax=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:pgmax,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :pgloc=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:pgloc,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :pgw=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:pgw,
       :must_pass=>
        [{:test=>"kind_of? Numeric",
          :explanation=>
           "This variable must be a floating point number (an integer is also acceptable: it will be converted into a floating point number)."}],
       :type=>:Float},
     :iremapon=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iremapon,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer},
     :iogyropsi=>
      {:should_include=>"true",
       :description=>nil,
       :help=>nil,
       :code_name=>:iogyropsi,
       :must_pass=>
        [{:test=>"kind_of? Integer",
          :explanation=>"This variable must be an integer."}],
       :type=>:Integer}}}}
